# GlamLuxeByHp — Convenciones del proyecto

E-commerce mayorista/minorista (marca blanca, sin estética definida todavía).
Stack obligatorio: Next.js (App Router) + TypeScript + React + Prisma + Supabase PostgreSQL + Cloudflare R2 + Stripe + Vercel + pnpm.

## Estado actual

- Sin branding/paleta de colores definida todavía: no introducir colores de marca, logo ni tokens de color personalizados. Sí construir componentes de UI **interactivos y profesionales** (Tailwind con paleta neutra por defecto, shadcn/ui donde aplique) — la calidad de interacción y estructura visual no espera a que exista una identidad de marca, solo el color/branding específico.
- No existe `IMPLEMENTATION_PLAN.md` en el repo — las 60 tickets (fases y descripciones) viven en el PDF "Tickets de GitHub - Moda HP" que el usuario provee fuera del repo, no en un archivo versionado. La sección "Referencia rápida de reglas de negocio" más abajo y las secciones por ticket de este archivo son el resumen que sí persiste en el repo.
- Por ahora se trabaja sin MCPs adicionales (Prisma MCP u otros) — todo vía CLI/herramientas estándar.

## Cómo trabajar en este repo (para minimizar tokens y maximizar calidad)

- **Código mínimo y sin sobreingeniería**: usar el enfoque de la skill `ponytail` por defecto en toda tarea de código (escribir, refactorizar, revisar). Nada de abstracciones especulativas, capas sin propósito, ni flags de compatibilidad hacia atrás en un proyecto que aún no tiene usuarios.
- **Exploración amplia del código → subagente**: cualquier búsqueda que tome más de 2-3 llamadas a Grep/Glob debe delegarse al agente `Explore` en vez de hacerse inline, para no inflar el contexto principal.
- **Antes de cerrar un ticket de código**: correr la skill `code-review` (o `simplify` si es solo limpieza) sobre el diff antes de darlo por terminado.
- **Sin comentarios explicativos** de qué hace el código (los nombres ya lo dicen); solo comentarios que expliquen un porqué no obvio.
- **Sí construir UI**, incluyendo componentes interactivos (modales, dropdowns, tabs, formularios con estados de carga/error, etc.) a medida que avanzan los tickets — lo único que se pospone es branding: colores de marca, logo y tokens de color personalizados.
- Server Components por defecto; Client Components solo donde hay interactividad real (carrito, checkout, formularios admin, Stripe Elements).
- Lógica de negocio (pricing mayorista, envío por tramos, máquina de estados de pedido) vive en `src/server/services/`, pura y testeable, no en Server Actions ni componentes.

## Base de datos (Prisma 7 + Supabase)

- Prisma pinneado a `7.10.0` (versión estable) a propósito — el tag `latest` de npm apunta a un release candidate de Prisma 8, no usarlo hasta que sea estable.
- Config del CLI en `prisma7.config.ts` (ese es el nombre que esta versión de Prisma detecta automáticamente, no `prisma.config.ts`). Ahí solo vive `DIRECT_URL` porque el CLI (migrate/db push/studio) la necesita.
- `DIRECT_URL` usa el **Session pooler** de Supabase (`aws-0-<region>.pooler.supabase.com:5432`), no el host de conexión directa real (`db.<project-ref>.supabase.co:5432`) — ese host solo resuelve por IPv6 y da `ETIMEDOUT` en redes/entornos sin salida IPv6 (verificado en desarrollo). El Session pooler soporta prepared statements igual que una conexión directa, así que sirve para migraciones sin ese problema.
- La app en runtime (`src/lib/prisma.ts`) usa `DATABASE_URL` (conexión pooled vía Supavisor/PgBouncer) directamente en el `PrismaPg` adapter — **no** pasa por `prisma7.config.ts`. El tipo `Datasource` de esta versión no tiene campo `directUrl`, por eso están separados así.
- Prisma 7 requiere **driver adapters** (no hay motor de query engine binario): usamos `@prisma/adapter-pg` + `pg`. El cliente generado no vive en `node_modules`, sino en `src/generated/prisma` (gitignored) — se importa como `@/generated/prisma/client` (el archivo `client.ts`, la carpeta no tiene `index`).
- Correr `pnpm db:generate` después de cualquier cambio en `prisma/schema.prisma`.

## Autenticación

- Sesión propia: JWT (librería `jose`, edge-safe) en cookie httpOnly (`src/lib/session.ts`), sin tabla de sesiones en DB. Contraseñas con `bcryptjs` (`src/lib/password.ts`).
- Cliente y administrador comparten el modelo `User` (`role`), pero tienen flujos y rutas completamente separados: `/login` + `/registro` (cliente, con auto-registro) vs. `/acceso-admin` (admin, sin auto-registro — se crea vía `pnpm db:seed` con `ADMIN_EMAIL`/`ADMIN_PASSWORD` en `.env`).
- `src/proxy.ts` protege `/admin/:path*` (requiere `role administrador`, si no redirige a `/acceso-admin`). En Next.js 16 el archivo se llama `proxy.ts` y la función `proxy`, no `middleware.ts`/`middleware` — ese nombre está deprecado desde v16. Corre en runtime Node.js por defecto (ya no Edge).
- Los Server Actions de auth siempre devuelven el mismo mensaje genérico ("Correo o contraseña incorrectos") sin importar si el correo no existe, la contraseña es incorrecta, o el usuario tiene el rol equivocado para ese formulario — evita filtrar qué cuentas existen o son admin.

## Design system (`src/components/ui/`)

- Tokens de color/radio en `src/app/globals.css` como variables CSS (`--background`, `--foreground`, `--card`, `--primary`, `--secondary`, `--muted`, `--border`, `--input`, `--ring`, `--destructive`, `--radius`) mapeadas a utilidades de Tailwind v4 vía `@theme inline` (ej. `--color-primary` → clases `bg-primary`/`text-primary`). Paleta neutra (grises) a propósito — cuando se defina la marca, el rebranding es cambiar estos valores en un solo lugar, no tocar cada componente.
- **Nunca usar clases `neutral-*`/`gray-*`/colores literales de Tailwind directamente en componentes** — siempre los tokens semánticos (`bg-background`, `text-foreground`, `text-muted-foreground`, `border-border`, etc.), para que el rebranding futuro no requiera tocar componentes.
- Variantes de componentes con `class-variance-authority` (`cva`) + `cn()` (`clsx` + `tailwind-merge`, en `src/lib/utils.ts`) — mismo patrón que usa shadcn/ui, así cualquier componente de shadcn se puede copiar/pegar directo sin reajustar tokens.
- Primitivos disponibles: `Button` (variants primary/secondary/outline/ghost/destructive, prop `loading` con spinner), `Input`, `Label`, `TextField` (Label+Input), `Card`/`CardHeader`/`CardTitle`/`CardContent`/`CardFooter`, `Badge`, `FormError`, `SubmitButton` (wrapper de `Button` con `useFormStatus`), `PriceDual` (precio mayorista + individual, patrón de negocio del PDF).

## Layout y navegación

- `src/app/(shop)/layout.tsx` envuelve todas las rutas de tienda (Home, login, registro, y las que vengan: tienda, producto, carrito, checkout, perfil, about, contacto, políticas) con `SiteHeader` + `SiteFooter`. `(admin)` (acceso-admin, admin) es una superficie aparte, sin este layout ni el header/footer de la tienda — a propósito, según el PDF.
- `SiteHeader` es Server Component (lee `getSession()` para mostrar "Mi cuenta"+logout o "Iniciar sesión"); el toggle del menú móvil vive aparte en `MobileNav` (Client Component) porque es la única parte que necesita estado en el cliente.
- Como el header depende de `getSession()` (usa `cookies()`), todas las rutas bajo `(shop)` son dinámicas (`ƒ` en el build), no estáticas — esperado, no es un bug.
- Contacto de WhatsApp en el footer es opcional vía `NEXT_PUBLIC_WHATSAPP_NUMBER`: si no está configurado, el link simplemente no se renderiza (no hay número real todavía).

## Cloudflare R2 (imágenes de producto)

- Cliente S3-compatible en `src/lib/r2.ts` (`@aws-sdk/client-s3`), configurado con el endpoint `https://<R2_ACCOUNT_ID>.r2.cloudflarestorage.com` y `region: "auto"`.
- Las subidas son siempre **server-side** (Server Actions del panel admin, ticket #11) usando `PutObjectCommand` directo — no se usan URLs firmadas ni upload desde el cliente, así que no hace falta configurar CORS en el bucket.
- `R2_PUBLIC_URL` es el dominio público desde el que se sirven los objetos (custom domain o `*.r2.dev`) — `r2PublicUrl(key)` arma la URL final; nunca se construye a mano en los componentes.
- Estructura de keys: `products/{productId}/{uuid}-{filename-sanitizado}` (`src/server/services/product-image-service.ts`, función `buildKey`).
- `ProductImage` guarda solo `key` (no `url`) — la URL pública siempre se deriva con `r2PublicUrl(key)` al leer, nunca se persiste. Así, si cambia `R2_PUBLIC_URL` (ej. de `*.r2.dev` a un dominio propio), no hay que migrar datos.
- Una sola `isPrimary: true` por producto no está forzado a nivel de base de datos (requeriría un índice único parcial que Prisma no modela bien) — se garantiza en `setPrimaryProductImage` (transacción: desmarca todas las del producto, marca la elegida) y en `addProductImage`/`deleteProductImage` (la primera imagen subida es primaria por defecto; al borrar la primaria se promueve la siguiente por `position`).
- Validación de imágenes: solo `image/jpeg|png|webp`, máx. 5MB (`assertValidImageFile`) — valida el MIME que reporta el navegador, no magic bytes; suficiente para un panel admin de bajo riesgo, no para un endpoint público.
- Todos los Server Actions de admin verifican `role administrador` al inicio con `requireAdmin()` (`src/lib/session.ts`) — es la única defensa real, la protección de `/admin/*` en `proxy.ts` no alcanza a un Server Action si se invocara desde otro lado. Reusar este helper en cada Server Action de admin nueva, no reescribirlo.
- `ProductImageUploader` (`src/components/admin/ProductImageUploader.tsx`) es el componente reutilizable para subir/reemplazar/borrar/marcar-principal — pensado para que el ticket #13 (CRUD de productos) lo monte directamente en el formulario de producto, recibiendo `images` ya con `url` calculada por el Server Component padre (nunca se expone `R2_PUBLIC_URL` al cliente).
- `next.config.ts` lee `R2_PUBLIC_URL` en build/dev time para autorizar ese host en `images.remotePatterns` (necesario para usar `next/image` con las imágenes de R2) — si cambian de dominio público, no hay que tocar el config, se recalcula solo.

## Panel admin: CRUD (categorías, y patrón para productos/etc. en adelante)

- `/admin/categorias` sigue el patrón estándar de CRUD admin de este proyecto: página lista (Server Component) + `/nueva` y `/[id]/editar` con un `CategoryForm` compartido (Client Component con `useActionState`) que recibe la Server Action ya bindeada (`updateCategoryAction.bind(null, id)`).
- Ticket #12 reinterpretó "eliminar (soft si tiene productos)" del plan original: en vez de agregar un campo `active` a `Category` (no existía y no hacía falta), el borrado simplemente se **bloquea con un mensaje claro** si tiene productos asociados (ya lo protege el `onDelete: Restrict` del ticket #8 a nivel de FK; el service pre-valida para dar un mensaje amigable con el conteo, en vez de dejar que reviente el constraint).
- Auto-generación de slug (`CategoryForm`) desde el nombre, pero **solo al crear** — al editar, el slug ya existente no se debe regenerar solo por tocar el nombre (se detectó y arregló este bug real durante la verificación: cambiar el nombre en modo edición estaba pisando el slug).
- `src/app/(admin)/admin/layout.tsx` es la nav mínima compartida de todo `/admin/*` (links + logout) — cada ticket nuevo de admin solo agrega su link ahí, no repite header/logout.
- `eslint.config.mjs` tiene `argsIgnorePattern`/`varsIgnorePattern: "^_"` para `no-unused-vars` — parámetros de Server Actions no usados (como `_prevState` cuando la action no necesita leer el estado previo) se prefijan con `_` y no generan warning.
- CRUD de productos (`/admin/productos`) sigue exactamente el mismo patrón que categorías, con dos diferencias: (1) `ProductForm` recibe la lista de categorías como prop (Server Component la carga) para el `SelectField`; (2) la página de editar producto monta además `ProductImageUploader` (ticket #11) debajo del formulario — las imágenes solo se gestionan una vez el producto existe (tiene `id`), nunca en el formulario de creación.
- `deleteProduct` (`product-service.ts`) borra primero los objetos de R2 de todas las imágenes del producto (reutilizando `deleteFromR2`, exportado desde `product-image-service.ts`) y luego borra el `Product` — el cascade de Prisma limpia las filas de `ProductImage`/`ProductVariant`, pero nunca toca R2, así que ese paso manual es obligatorio o quedan objetos huérfanos en el bucket.
- Primitivos de UI nuevos: `Textarea`, `Select`, `SelectField` (Label+Select, mismo patrón que `TextField`), `Checkbox` (input+label a la derecha). Igual que el resto del design system, solo tokens semánticos, cero colores hardcodeados.
- `VariantManager` (ticket #14, en la página de editar producto) gestiona tallas/stock con una fila por variante, cada una con su propio `useActionState` (patrón `VariantRow`, igual que `ProductImageCard` del ticket #11) — permite editar stock/talla o borrar sin afectar el estado de las demás filas. La gestión de variantes se muestra **siempre** en la página de editar, sin importar si el checkbox "Tiene variantes de talla" está marcado — ese flag es solo informativo para el storefront (tickets #17/#19), no condiciona si el admin puede cargar tallas.
- Duplicar una talla para el mismo producto se bloquea con mensaje claro (`assertSizeAvailable` en `product-variant-service.ts`), mismo patrón de pre-validación que categorías/productos en vez de dejar reventar el `@@unique([productId, size])`.

## Tienda pública (`src/app/(shop)/`)

- Home (ticket #15) muestra "categorías destacadas" y "productos destacados" sin curación manual todavía: `listFeaturedCategories` (`category-service.ts`) = categorías con productos activos ordenadas por cantidad de productos activos (desc) y nombre como desempate; `listFeaturedProducts` (`product-service.ts`) = productos activos más recientes (`createdAt` desc, `id` desc como desempate). Si más adelante se necesita curación real (ej. un checkbox "destacar" en el admin), se agrega un campo explícito — no inferir featured de otra señal.
- `Product.createdAt` (`@default(now())`) se agregó en el ticket #15 solo para poder ordenar "más reciente primero"; los productos creados antes de esa migración comparten el mismo timestamp de backfill, por eso el `orderBy` tiene `id` como desempate.
- `listFeaturedCategories` no puede pedirle a Prisma que ordene por un `_count` ya filtrado (activo únicamente) a nivel de base de datos — Prisma solo soporta `orderBy` sobre el conteo total de la relación — así que trae un lote acotado (`take: Math.max(limit * 5, 50)`) y ordena/recorta en JS. No "simplificar" esto a un `orderBy: { products: { _count: 'desc' } }` en Prisma: cambiaría el criterio a "más productos totales" en vez de "más productos activos".
- `src/components/shop/CategoryCard.tsx` y `ProductCard.tsx` enlazan a `/tienda` y `/producto/[slug]` — ambas rutas ya existen (tickets #16/#17).
- `/tienda` (ticket #16) lista productos activos con filtro opcional `?categoria={slug}`. `listShopCategories` (`category-service.ts`) solo trae categorías con productos activos, sin conteo — a diferencia de `listFeaturedCategories`, no necesita el workaround de ordenar en JS porque el filtro de tienda no rankea, solo lista. `toProductCardItem` (`product-service.ts`) es el mapeo compartido de un `Product` con `category`+`images` incluidos hacia las props de `ProductCard`; vive en el service (no en el componente) para que `ProductCard.tsx` no importe `r2PublicUrl`/el cliente de R2 — si un componente cliente futuro reusa `ProductCard`, no arrastra el SDK de S3 al bundle del navegador.
- Un slug de categoría inválido o sin productos activos en `/tienda?categoria=X` no se trata como "sin filtro": la píldora "Todas" no se resalta y el mensaje distingue "no encontramos esa categoría" de "aún no hay productos" — no inferir "todas" solo porque no hubo match.
- `/producto/[slug]` (ticket #17): `getProductBySlug` filtra `active: true`, así que un producto desactivado da 404 en su propia página de detalle aunque se acceda por link directo — igual que ya lo excluye `/tienda`. `ImageGallery` (`src/components/shop/ImageGallery.tsx`) es Client Component (única parte con estado: click en miniatura cambia la imagen principal) y recibe `initialIndex` calculado por la página a partir de `ProductImage.isPrimary` — no asume que la primera imagen por `position` es la principal, porque un admin puede marcar cualquier imagen como principal sin reordenarlas, y así coincide con la miniatura que ya vio en Home/Tienda.
- Las tallas (`ProductVariant.size`) son texto libre, no enum, así que ordenarlas con `orderBy: { size: "asc" }` de Prisma las deja en orden alfabético (L, M, S, XL) o incluso numérico roto ("10" antes que "2"). `sortVariantsBySize` (`product-service.ts`) reordena en JS con una lista de tallas de letra conocida + fallback numérico + fallback alfabético — se aplica tanto en `getProductBySlug` (tienda) como en `getProduct` (admin) para que el orden nunca difiera entre panel y storefront.
- El botón "Agregar al carrito" en la página de producto muestra siempre `AddToCartForm` (selector de talla si `hasVariants`, cantidad) — desde el ticket #22 no requiere sesión, ver sección "Carrito" para el carrito de invitado. La lista de solo lectura de tallas (`Badge` por talla, "(agotado)") se mantiene aparte porque es lo único que un componente puramente informativo necesita mostrar.

## Carrito (`src/server/services/cart-service.ts`, ticket #18; invitado + fusión, ticket #22)

- El carrito **sí admite invitados**: `Cart.userId` y `Cart.sessionToken` son ambos opcionales pero mutuamente excluyentes (`CartOwner` en `cart-service.ts`, reforzado por un `CHECK` de Postgres agregado a mano en la migración `guest_cart_session_token` — Prisma no modela check constraints en el schema). Un invitado se identifica por una cookie opaca httpOnly (`cart_session`, `src/lib/cart-session.ts`) creada la primera vez que agrega algo al carrito — nunca al solo visitar una página, para no crear filas de `Cart` por cada visitante. `/carrito` ya **no** está en el `matcher` de `src/proxy.ts`; solo `/admin` y `/perfil` siguen requiriendo sesión.
- `resolveCartOwnerForRead()` (páginas/`SiteHeader`, no puede escribir cookies) vs. `resolveCartOwnerForWrite()` (Server Actions, sí puede crear la cookie de invitado) en `src/lib/cart-session.ts` — todas las funciones de `cart-service.ts` reciben un `CartOwner` (`{ userId }` o `{ sessionToken }`) en vez de un `userId` suelto.
- Al iniciar sesión o registrarse (`auth-actions.ts`), `mergeGuestCartIntoUser` fusiona el carrito de invitado (si existe) reusando `addToCart` línea por línea — así la fusión revalida stock/producto activo igual que un `addToCart` normal, y una línea con `CartError` (producto desactivado, sin stock suficiente) se descarta en vez de bloquear el login. El carrito de invitado se **borra antes** de fusionar sus líneas (no después): `addToCart` suma cantidades y no es idempotente, así que si el proceso falla a mitad del fusionado, un reintento del login no debe volver a encontrar ese carrito y duplicar líneas ya fusionadas — perder lo que faltaba es preferible a duplicar cantidades. `mergeGuestCartOnAuth` además nunca deja que un fallo ahí tumbe el login/registro (la cookie de sesión ya se asignó en ese punto).
- Límite aceptado, no un bug pendiente: dos clics de "agregar al carrito" casi simultáneos de un mismo invitado *sin cookie todavía* pueden generar dos `Cart` de invitado distintos (cada request ve la cookie ausente y crea la suya); el navegador se queda con el `Set-Cookie` que llegue último y el otro carrito queda huérfano. Inherente a cualquier esquema de cookie perezosa; el costo de eliminarlo (cookie asignada por adelantado a cada visitante desde `proxy.ts`, ampliando su `matcher` a todas las rutas) no se justifica frente al impacto (como mucho, un artículo perdido en un doble clic de un visitante nuevo).
- `WHOLESALE_ITEM_THRESHOLD` (6, en `cart-service.ts`) vive en un solo lugar: al llegar la suma de cantidades del carrito a ese umbral, **todas** las líneas cambian a `wholesalePrice` (no solo las nuevas). Envío estimado: $10 (1-2 artículos) / $35 (3-5), igual que la referencia de negocio; en el tramo mayorista `shippingEstimate` es `null` ("se coordina aparte") porque el PDF solo documenta tramos a nivel individual.
- `CartItem` tiene `@@unique([cartId, productId, variantId])`, pero Postgres no deduplica `NULL`, así que esa unicidad solo protege productos **con** talla (`variantId` no nulo) — el caso donde importa por el stock limitado. `addToCart` usa `cart.upsert` (evita la carrera al crear el primer carrito de un dueño, sea `User` o invitado) y atrapa el error de constraint único del `create` de `CartItem` para convertirlo en un incremento de cantidad en vez de un 500, cubriendo el caso de doble clic/doble pestaña.
- Cantidad tiene tope de 9999 (`quantityField` en `cart-actions.ts`) — sin esto, un input manipulado podía mandar un entero fuera de rango de Postgres y tumbar la acción con un error crudo en vez de un mensaje.

## Perfil y direcciones (`src/server/services/address-service.ts`, ticket #19)

- `/perfil` existía como destino de redirect desde `/login`/`/registro` desde el ticket de auth, pero no tenía página (404) hasta este ticket. Se aprovechó para construir el CRUD completo de `Address` (modelo ya definido en el schema desde el inicio, sin usar) en vez de solo un placeholder: el checkout va a necesitar direcciones de todas formas. Protegido vía `proxy.ts` (`matcher` incluye `/perfil/:path*`) + `requireCustomer()` en cada página/action — a diferencia de `/carrito` (ticket #22), `/perfil` sigue exigiendo cuenta porque un invitado no tiene nada que ver ahí.
- `Address.userId` es opcional en el schema (pensado para checkout de invitado a futuro), pero este ticket **no** lo explota: todo el CRUD exige `userId` no nulo vía `requireCustomer()`. `getOwnedAddress`/`getAddressForEdit` rechazan una dirección con `userId: null` igual que una de otro usuario — no se puede "adoptar" una dirección huérfana.
- `notes` en el formulario se transforma a `null` (no `undefined`) cuando queda vacío — Prisma trata `undefined` en `update()` como "no tocar la columna", así que un `undefined` aquí dejaría una nota vieja imposible de borrar desde el formulario. Mismo cuidado aplica a cualquier campo opcional futuro que use `update()`.
- `getOwnedAddress` valida que el `id` tenga forma de UUID antes de consultar Postgres — sin eso, un id inválido (typeado a mano en la URL, o un id de otra tabla) revienta con un error crudo de Postgres en vez de un 404/mensaje amigable. `getAddressForEdit` es la variante que devuelve `null` en vez de lanzar (mismo patrón que `getProductBySlug` del ticket #17), para que la página de editar solo necesite `if (!address) notFound()`.
- `DeleteAddressButton` sí es Client Component con `useActionState` (a diferencia de un borrado sin estado): si `deleteAddress` lanza `AddressError` (doble clic, dos pestañas), se muestra el mensaje en vez de reventar la Server Action sin control — mismo patrón que `DeleteCategoryButton`/`DeleteProductButton` en el admin.
- Sin campo de "dirección principal/predeterminada" todavía — cuando el ticket de checkout necesite elegir una dirección de envío entre varias, se agrega ese campo explícito en `Address`, no se infiere de otra señal (mismo criterio que "featured" en tickets #15/#16).

## Pedidos (`Order`/`OrderItem`, ticket #23)

- Ticket puramente de schema (como #3/#8/#18): solo se crearon los modelos y sus enums, sin `order-service.ts` ni checkout todavía — eso llega en los tickets #24 en adelante. Estos modelos se diseñaron a partir de las referencias explícitas en las descripciones de los tickets #24-#39 del PDF de tickets (ver "Estado actual" arriba), documentadas aquí para que el resto de la Fase 4/5/6 no tenga que adivinar la forma otra vez.
- A diferencia del ticket #19 (Address/Perfil, que era CRUD sobre un modelo ya definido desde #3 y por eso declinó agregar un campo — "dirección principal" — que ningún ticket pedía todavía), **este** ticket es el que define el schema: comprometerse ahora con `termsAcceptedAt`/`reservedUntil` como columnas (aunque nada las llena hasta #25/#27) no es la misma sobreingeniería que #19 evitó, porque esos dos campos sí están nombrados explícitamente en las descripciones de #25 y #27 — no son un concepto de negocio inventado por adelantado.
- `Order.userId` es opcional, igual que `Address.userId` — pensado para checkout de invitado a futuro (el carrito ya lo admite desde el ticket #22), no explotado todavía.
- `Order` **no tiene una relación a `Address`**: copia sus mismos campos (`fullName`, `whatsapp`, `email`, `addressLine`, `addressType`, `city`, `state`, `zip`) como snapshot al momento de crear el pedido (ticket #24 los copia 1:1 desde el `Address` elegido). Igual que con los precios (ver siguiente punto): un pedido ya hecho no debe cambiar si el cliente edita o borra esa dirección guardada después desde `/perfil`. A propósito **no** tiene tampoco un `addressId` de solo-referencia (a diferencia de `OrderItem.productId`, ver abajo): el punto del snapshot es que nadie necesite "ver la versión actual" de la dirección de un pedido ya hecho, mientras que sí tiene sentido poder linkear al producto actual de una línea de pedido desde el admin.
- `Order.pricingTier`, `subtotal`, `shippingCost` y `total` se congelan al confirmar el pedido — a diferencia del carrito (que recalcula todo en vivo en `getCartWithPricing`), un pedido es un registro histórico: no debe moverse si después cambia `WHOLESALE_ITEM_THRESHOLD`, una tarifa de `ShippingRate`, o el precio de un producto. `shippingCost` es `null` en el tier mayorista, igual que `shippingEstimate` en el carrito ("se coordina aparte"); en ese caso `total` se guarda igual a `subtotal` — el envío se factura aparte, `total` nunca queda en `null` ni asume envío gratis.
- `OrderItem` tampoco vive de una relación viva a `Product`/`ProductVariant`: guarda `productName`/`variantSize`/`unitPrice` como snapshot, y `productId` es **opcional** con `onDelete: SetNull` — solo de referencia para el panel admin, no la fuente de verdad. Así `deleteProduct` (ticket #13) puede seguir borrando productos (incluyendo sus imágenes de R2) sin que eso rompa o borre el historial de pedidos que ya los incluían. Verificado contra la base real: borrar el producto de un pedido existente deja `OrderItem.productId` en `null` y conserva `productName`/`unitPrice` intactos.
- `OrderStatus`: `reservado` (default, al crear el pedido) → `confirmado` (pago verificado, ticket #32/#34) → `enviado` (admin, ticket #38). Alternos terminales: `vencido` (cron del ticket #28, reserva de 3 días expirada sin pago) y `cancelado` (pago manual rechazado, ticket #34). El ticket #35 (`OrderStateMachine`) es el que va a centralizar qué transiciones son válidas (p.ej. `reservado`→`enviado` directo no debería ser posible) — este ticket solo define el enum, no la máquina de estados.
- `Order.paymentMethod` (tarjeta/zelle/cashapp/paypal) se captura en el pedido mismo porque el ticket #26 (selección de método) ocurre *antes* de que exista el modelo `Payment` (ticket #30) — `Payment` va a trackear la verificación/estado de ese cobro, `Order.paymentMethod` es solo qué opción eligió el cliente al pagar.
- `Order` tiene `@@index([status, reservedUntil])` (no solo `status`) porque sirve directo la consulta que el propio ticket #28 describe: pedidos `reservado` cuya reserva ya venció.
- `OrderItem.variantId` (opcional, `onDelete: SetNull`, agregado en el ticket #28) es la excepción a "OrderItem no vive de relaciones vivas" de arriba: a diferencia de `productId` (solo para linkear desde el admin), este campo tiene un uso operativo real — el cron de expiración necesita saber exactamente qué `ProductVariant` devolver al stock, y `variantSize` (el snapshot de texto) no alcanza para eso de forma confiable si el admin renombra o recrea una talla.

## Checkout (`/checkout/*`, ticket #24 en adelante)

- **Checkout exige cuenta de cliente** (`requireCustomer()` en cada página + `/checkout/:path*` en el `matcher` de `proxy.ts`, mismo patrón que `/perfil`) — a propósito, no un descuido, aunque `Cart`/`Address`/`Order.userId` sean todos "guest-ready" desde los tickets #22/#23. Ninguna de las 60 tickets del PDF describe un flujo de checkout de invitado (solo el carrito lo admite); el guest-cart existe para que alguien pueda armar su pedido sin cuenta, pero tiene que iniciar sesión o registrarse para pagarlo — y ahí es donde `mergeGuestCartIntoUser` (ticket #22) entra en juego. Si una ticket futura pide checkout de invitado de verdad, el schema ya no necesita migración — solo quitar este gate.
- El estado entre pasos del wizard (dirección elegida en el paso 1, más lo que agreguen los pasos 2/3) viaja por **query string** (`/checkout/resumen?addressId=...`), no por una cookie/tabla de "borrador de checkout" — para 2-3 campos es la opción más simple, y una dirección elegida ya persiste como `Address` real (no hay nada que "guardar en borrador"). Esto no escala indefinidamente: si un paso futuro necesita acumular más estado del que cabe cómodo en la URL, ahí sí conviene reconsiderar.
- `/checkout/resumen` (paso 2, ticket #25) es el primer punto que *lee* `?addressId=`, un query string editable por el usuario: revalida dueño con `getAddressForEdit` (chequeo de forma UUID + `address.userId === session.userId`) antes de mostrar nada, y redirige de vuelta a `/checkout/direccion` si no resuelve a una dirección propia — un `findUnique` directo ahí habría sido el IDOR real que este mismo archivo advertía en el ticket anterior. `acceptCheckoutTermsAction` revalida el mismo `addressId` otra vez del lado del POST, en vez de confiar en que llegó intacto desde la página.
- Crear una dirección durante el checkout (`createCheckoutAddressAction`) usa el mismo `createAddress` de `/perfil` — la dirección queda guardada permanentemente en la cuenta del cliente, no es un dato de un solo uso. No hay (ni se necesita) un modelo de dirección "efímera" separado.
- `parseAddressInput` (`address-service.ts`) centraliza el `addressSchema.safeParse` que antes estaba repetido en `createAddressAction`/`updateAddressAction`/`createCheckoutAddressAction` — un solo lugar si cambia una regla de validación.
- `Order.termsAcceptedAt` viaja como query string entre pasos (`?termsAcceptedAt=...`, generado por `acceptCheckoutTermsAction` al aceptar el checkbox) solo como señal de "paso 2 completado" — es un valor editable por el cliente que ningún paso revalida contra nada. `confirmCheckoutOrderAction` (ticket #27) **no lo persiste tal cual**: `createReservedOrder` (`order-service.ts`) regenera `termsAcceptedAt` con `new Date()` en el servidor al crear el pedido, precisamente para no guardar un consentimiento legal falsificable.
- `/checkout/pago` (paso 3, ticket #26): selector de método de pago (`PaymentMethodForm` + `selectCheckoutPaymentMethodAction`), puramente de UI — no procesa ningún pago. Revalida `addressId` contra la base (mismo `getAddressForEdit` que los pasos 1/2, ahora extraído a `requireCheckoutCartAndAddress` en `src/lib/checkout.ts` — ver más abajo) y solo verifica que `termsAcceptedAt` venga presente en el query string (no lo revalida contra nada: sigue siendo el valor editable por el cliente que el punto anterior describe). Reenvía los tres valores (`addressId`, `termsAcceptedAt`, `paymentMethod`) por query string a `/checkout/confirmar` (ticket #27, referencia hacia adelante — da 404 hasta esa ticket). Primitivo de UI nuevo: `Radio` (mismo patrón que `Checkbox`, input+label a la derecha, pero `type="radio"` con `id` derivado de `name`+`value` para que varias opciones del mismo grupo no colisionen).
- `requireCheckoutCartAndAddress(userId, addressId)` (`src/lib/checkout.ts`) centraliza el guard que ya se repetía en `/checkout/resumen` y `/checkout/pago` (carrito no vacío → redirect a `/carrito`; `addressId` de dueño inválido → redirect a `/checkout/direccion`) — vive en `src/lib/` y no en `src/server/services/` porque llama a `redirect()` de Next.js, un efecto de framework que la capa de servicios (pura, testeable) no debe tener. Los Server Actions correspondientes (`acceptCheckoutTermsAction`, `selectCheckoutPaymentMethodAction`) **no** usan este helper: ahí una dirección inválida se muestra como `{error}` en el propio formulario en vez de expulsar al cliente a otra página, un comportamiento distinto a propósito.
- El propio ticket #26 del PDF pide mostrar "solo los métodos habilitados en `PaymentMethodConfig`", pero ese modelo no existe hasta el ticket #36 — igual que el ticket #12 reinterpretó "soft delete" sin un campo `active` que no existía todavía, `PAYMENT_METHOD_OPTIONS` (`payment-service.ts`) por ahora es una lista estática con los cuatro métodos (`tarjeta`/`zelle`/`cashapp`/`paypal`) siempre visibles. El ticket #36 es el que la convierte en un filtro dinámico sobre esa tabla.
- `/checkout/confirmar` (paso 4, ticket #27): última pantalla del wizard — repite el resumen (`OrderSummary`, extraído de `/checkout/resumen` para no triplicar esa JSX) más el método elegido, y su único botón ("Confirmar pedido") llama a `confirmCheckoutOrderAction`, que crea el `Order` de verdad (`createReservedOrder` en `order-service.ts`) y redirige a `/pedidos/[id]` (implementada en el ticket #29 — ver esa sección más abajo). Sigue el mismo patrón que los pasos anteriores: validación de formato/dueño antes de la única llamada cara (acá, la creación del pedido).
- `createReservedOrder` (`order-service.ts`) recalcula `pricingTier`/`subtotal`/`shippingCost`/`total` (vía `computeCartTotal`, compartida con `CartTotals` para que la fórmula del total nunca diverja entre lo que se muestra y lo que se cobra) con un `getCartWithPricing` fresco — nunca confía en nada que haya viajado por query string. Toda la mutación (reclamar el carrito, descontar stock, crear `Order`/`OrderItem`) ocurre dentro de un mismo `prisma.$transaction`.
- **El propio carrito es la sección crítica que evita pedidos duplicados**: lo primero que hace la transacción es `tx.cart.deleteMany({ where: { userId } })` y comprobar `count > 0` — si dos confirmaciones del mismo carrito llegan casi a la vez (doble clic, dos pestañas), la segunda transacción encuentra 0 filas para borrar (la primera ya se lo llevó) y aborta con un error claro, sin tocar stock ni crear nada. Este orden importa: mover el `deleteMany` al final (como en la primera versión de este ticket) NO sirve — ambas confirmaciones ya habrían leído el mismo carrito, decrementado el stock (dos veces, si alcanzaba para ambas) y creado dos `Order` antes de que cualquiera intentara borrar el carrito.
- El descuento de stock usa `productVariant.updateMany({ where: { id, stock: { gte: quantity } }, data: { stock: { decrement: quantity } } })` — el propio `UPDATE` con la condición de stock en el `WHERE` es la sección crítica atómica que evita que dos checkouts simultáneos vendan la misma última unidad dos veces; si `result.count === 0`, se aborta con un mensaje claro y la transacción completa se revierte.
- `getCartWithPricing` es de solo lectura (pensada para mostrar el carrito) y no filtra `product.active` como sí hace `addToCart` — mostrar una línea de un producto desactivado en el carrito es inofensivo, pero cobrarla no. `createReservedOrder` revalida `item.productActive` (campo agregado a `getCartWithPricing` en este ticket) dentro de la misma transacción, antes de descontar stock o crear el pedido.
- El ticket #27 del PDF pide también "registrar `InventoryLog`", pero ese modelo no existe hasta el ticket #39 — mismo tipo de reinterpretación que `PaymentMethodConfig` en el ticket #26: por ahora solo se descuenta `ProductVariant.stock`, sin dejar un registro de movimiento. El ticket #39 agrega ese log en el mismo punto de `order-service.ts`.
- Productos sin variantes (`hasVariants: false`) no tienen ningún campo de stock en el schema (`Product` nunca tuvo uno, ver ticket #8) — `createReservedOrder` solo descuenta stock para líneas con `variantId`, igual que `cart-service.ts` solo valida disponibilidad cuando el producto tiene variantes. No es una omisión de este ticket, es el mismo diseño ya establecido.

## Cron de expiración de pedidos (ticket #28)

- Primer Route Handler del proyecto: `src/app/api/cron/expire-orders/route.ts` (`GET`), disparado por Vercel Cron según `vercel.json` (`schedule: "0 * * * *"`, cada hora — no lo especifica el ticket; una hora es un grano razonable frente a los 3 días de `RESERVATION_DAYS`, se puede ajustar en el ticket #58 según el plan de Vercel real al desplegar — el plan Hobby limita la frecuencia mínima de los crons).
- Protegido con `CRON_SECRET` (`.env`): compara el header `Authorization: Bearer <CRON_SECRET>` que Vercel agrega automáticamente en producción a las llamadas de cron; sin el secreto correcto, devuelve 401. Mismo patrón que `AUTH_SECRET`, secreto distinto por entorno.
- `expireReservedOrders()` (`order-service.ts`) busca `Order` con `status: reservado` y `reservedUntil` vencido (el índice `@@index([status, reservedUntil])` del ticket #23 existe justo para esta consulta) y, por cada uno, en su propia transacción: reclama el pedido con `order.updateMany({ where: { id, status: "reservado" } })` antes de tocar nada — mismo patrón de "sección crítica atómica" que el reclamo del carrito en `createReservedOrder` (ticket #27), para que dos corridas del cron solapadas no liberen el mismo stock dos veces — y libera stock con `productVariant.updateMany({ where: { id: item.variantId }, data: { stock: { increment: quantity } } })` (no `update`: si la talla ya no existe, `OrderItem.variantId` es `SetNull`... salvo que la fila ya cargada en memoria todavía tenga el id viejo, en cuyo caso `updateMany` simplemente afecta 0 filas en vez de lanzar `RecordNotFound`).
- Igual que en el ticket #27, no se registra `InventoryLog` (ticket #39) — esta liberación de stock tampoco deja un movimiento todavía.
- Transacciones por pedido, no una sola transacción para todo el lote: si un pedido tiene un problema (fila bloqueada, etc.), no debe hacer rollback de los demás pedidos que sí pudieron expirarse en la misma corrida.

## Página de confirmación de pedido (`/pedidos/[id]`, ticket #29)

- Es exactamente el destino al que `confirmCheckoutOrderAction` (ticket #27) ya redirigía — cierra ese forward-reference. Protegida en `proxy.ts` (`matcher` ahora incluye `/pedidos/:path*`, redirige a `/login` sin sesión) + `getOrderForCustomer(userId, id)` (`order-service.ts`), que valida forma UUID y `order.userId === session.userId` antes de devolver el pedido — mismo patrón IDOR-safe que `getAddressForEdit`, y devuelve 404 (no un mensaje distinto) tanto para un id ajeno como para uno inexistente o mal formado, para no filtrar cuáles existen.
- `isUuid` (antes un `UUID_PATTERN` duplicado solo en `address-service.ts`) se extrajo a `src/lib/utils.ts` — ya son dos consumidores (`address-service.ts`, `order-service.ts`) y es razonable que un futuro `/admin/pedidos/[id]` (ticket #38) o el historial del cliente (ticket #44) sea un tercero.
- Reutiliza `OrderSummary` (extraído en el ticket #27) una tercera vez: los campos snapshot de `Order` (`fullName`/`addressLine`/etc.) se remapean al shape que espera `AddressSummary`, y `OrderItem.unitPrice * quantity` se calcula al vuelo como `lineTotal` (el snapshot no lo guarda precalculado, a diferencia de `getCartWithPricing`).
- Maneja los 5 valores de `OrderStatus`, no solo `reservado` — aunque hoy es el único estado alcanzable justo después del checkout, esta página va a seguir siendo el destino cuando otras tickets (#32/#34 confirman, #38 marca enviado, el cron del #28 vence) cambien el estado después, y un cliente puede volver a visitar la misma URL en cualquier momento.
- `getOrderStatusMessage(status, paymentMethod)` (`order-service.ts`) es el copy de "siguientes pasos". Para `reservado` con `tarjeta` o con un método manual (zelle/cashapp/paypal) el texto es un placeholder honesto ("te avisaremos"/"te contactaremos") — el pago en línea real con Stripe (ticket #31) y las instrucciones de pago manual desde `PaymentMethodConfig` (ticket #33) todavía no existen. No promete una función ya construida.
- `formatDate` (nuevo en `src/lib/utils.ts`, `Intl.DateTimeFormat("es-ES")`) es el primer formateador de fechas del proyecto — mismo patrón que `formatCurrency` (un solo `Intl` compartido, no instanciar uno por componente).

## Referencia rápida de reglas de negocio (fuente: PDF de análisis)

- Precio mayorista automático a partir de 6 artículos en el carrito (umbral configurable, no hardcodear el número 6 dos veces).
- Envío por tramos a nivel individual: $10 (1–2 artículos), $35 (3–5).
- Pedido se reserva 3 días; no se confirma hasta verificar el pago.
- Pago con tarjeta = Stripe (automático); Zelle/Cash App/PayPal = verificación manual por admin.
- Venta final: sin devoluciones salvo daño de fábrica reportado en 24h.
- Autenticación de cliente y de administrador son flujos y rutas separadas (`/login` vs `/acceso-admin`).
